# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_url', models.URLField(verbose_name='destination url')),
                ('tiny_url', models.CharField(max_length=10, verbose_name='tiny url')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('visit_counter', models.IntegerField(default=0, verbose_name='visit counter')),
            ],
        ),
    ]
