# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='tiny_url',
            field=models.CharField(max_length=10, unique=True, verbose_name='tiny url'),
        ),
    ]
